### ISSUE TITLE
Powerpoint support

### ISSUE THREAD

**Issue by krovvidi007** [hhurz/tableExport.jquery.plugin#107]
I don't see a powerpoint export option. Is there a plan to add it? 

Is there a working sample package that i can download? 

Thanks!

**Comment by hhurz** [comment]
My version of the plugin I forked from https://github.com/kayalshri/tableExport.jquery.plugin
The original version did offer an option to export to powerpoint but that never worked for me. Additionally I'm in doubt if it makes sence to export a html table into a powerpoint slide, because it would be possible to import data from excel into powerpoint too. Thus I decided to drop the powerpoint support in my fork of the plugin.

**Comment by krovvidi007** [comment]
Thank you for the update! 

Yeah the powerpoint download feature from the original plugin did not work for me either.  Unfortunately our project requires us to export to powerpoint.
