### ISSUE TITLE
bootstrap table filter control select options are passed to table export header/column name 

### ISSUE THREAD

**Issue by ysaadh** [hhurz/tableExport.jquery.plugin#147]
The problem is that when I use both bootstrap.table.filter.control and bootstrap.table.export, I get select options concatenated to the column names of the table in the header row.

also when use "data-tableexport-value" still export all select control options
so i suggest to update the  "parseString" function to avoid this error when using select filter control
with out using "data-tableexport-value" to be 
    if ($cell.data("filter-control") != undefined) {
          if ($cell.data("filter-control") == "select")
              htmlData = $cell[0].innerText;
          else
              htmlData = $cell.html();
      }
      else {
htmlData = $cell.html();
....
}

**Comment by hhurz** [comment]
Thanks for reporting this issue. Although it could be solved by implementing onCellHtmlData as described here #66, I decided to integrate this special bootstrap-table handling into the plugin. The fix will be available in release v1.7.1 which will be published soon

Note: The fix of this issue also covers issues #44, #66 and [bootstrap-table issue 1971](https://github.com/wenzhixin/bootstrap-table/issues/1971)

**Comment by jvarn** [comment]
Hello @hhurz ,
I'm experiencing the same two issues using 1.13.1.
[https://codepen.io/jvarn13/pen/BMNxvz](https://codepen.io/jvarn13/pen/BMNxvz)

In this example, please note that on export:

1. The first column heading appears as: "NameBethFredJohnMary"
`<th data-field="fullname" data-filter-control="select" data-sortable="true">Name</th>`

2. The second column heading is "Age for export" instead of "Age":
`<th data-field="ageforexport" class="d-none" data-tableexport-display="always" data-tableexport-value="Age">Age for export</th>`
