### ISSUE TITLE
New lines and html

### ISSUE THREAD

**Issue by mrbeak** [hhurz/tableExport.jquery.plugin#151]
Hallo,

I've been experimenting for hours with this plugin. I finally decided to ask for help.
I created a jsfiddle: http://jsfiddle.net/hvyowrgn/
I want wo export the table you se there.

Thanks to "styles": {"overflow": "linebreak"}, I manage to get the entire content but there are still some improvements I'd like to see:

1. interprete br-tags in the tablecells and display the content in a new line
2. Interprete the b-tags and display the content bold (if posible)
3. Adjust the column width automatically like the browser does (the last 2 columns need more space than the first ones)
4. not most important but the first layout from https://simonbengtsson.github.io/jsPDF-AutoTable/#themes looks quite nice but doesnt seem to be default here. how comes?

I would appreciate some hints and help with the config. I Really could'nt manage anything of this and wonder by now if everything of the above is actually posible.

thanks!

**Comment by hhurz** [comment]
Thanks for your questions and suggestions. Let me make some comments step by step:
- You manged to get the entire content by using the style options you mentioned. Alternatively there is an extended setting for the jspdf option "format" called "bestfit". This tries to select the best paper format so that the table content totally fits into it. (There is a short example in the readme.md)
- br-tags and html text styling in cells are currently not supported when exporting in pdf format. They are supported for excel format only. I'll put this issue on to the growing list of feature requests...
- Automatically column sizing is working for me. Perhaps I don't understand that issue.
- tableExport has its own (better looking ?) default styling, thats the only reason for the different looking. I changed your [jsfiddle](http://jsfiddle.net/hvyowrgn/1/) so the export result looks more like you want it. 
- In your jsfiddle you used an outdated version of jspdf. I updated it to a more rescent version.

**Comment by mrbeak** [comment]
Thank very much for your reply. 
So I wonder isn't there any way to force a linebreak? Maybe if br tags are not interpreted it is posible with onBeforeAutotable to replace them with something like /n which will cause a linebreak in the cell? Could you hint out if there might be a way?
Best

**Comment by mrbeak** [comment]
Sir, I just realised that the **jsfiddle I gave you was not correct**. I'm extremely sorry for that mistake :(

You must have thought my post doesn't make any sense. Please have a look here http://jsfiddle.net/hvyowrgn/2/ and you will understand my comments much better:

- The newline questtion remains as the most important one (th content of the last cell seems illegible otherwise)
- Here you see the column width is not adjusted automatically but every column takes an equal part althoug some would need more space.

Sorry again and I hope you can help me with the last  remaining points.

**Comment by hhurz** [comment]
Although I think your demands exceed the scope of this plugin, I was curious and played a bit with [jsPDF](https://github.com/MrRio/jsPDF) and [jsPDFAutotable's](https://github.com/simonbengtsson/jsPDF-AutoTable) output features. This resulted in a new release of the plugin, that offers pdf output with basic support of html text formatting elements (b, i, and br tags). In combination with the bestfit format option, I nearly get your desired output result (see [jsFiddle](http://jsfiddle.net/hvyowrgn/3)). 
In case this still doen't work for you, the plugin provides a new callback function ```onAutotableText``` that you could use to enhance the output by yourself.

**Comment by mrbeak** [comment]
Oh wow, this is amazing! Thank you so much.

I think however, the update also affected the old example (http://jsfiddle.net/hvyowrgn/2/): the proporty overflow:linebreak seems to be ignored now. Could this be a bug caused by the update?

**Comment by hhurz** [comment]
Thanks for testing. Just released version 1.8.1 that contains a fix.

**Comment by mrbeak** [comment]
Great work so far, really!
I've been testing a bit more and found some issues. Example here: http://jsfiddle.net/hvyowrgn/4/

1. The bold letters take more space than normal ones. However the following non-bold words start a bit too far left, just as if the word before wouldn't be bold. (See first row, last column, first line. The ":" is somewhere behin the "e" of "type". Also a bit more down in "cn:" or "uid:" the ":" is always too close to the word before.
2. The {"overflow": "linebreak"} works great for the non-html columns like the forth one called "Objekt". In the last column the mebisASVUID is still cut.
3. (just for my specific usecase but maybe you can provide help anyway). Would there be a way to have the linebreaks after the ":" instead of before? (see first row. last column after "mail").

Thank you for all the time you are putting into that plugin. It's amazing.

**Comment by hhurz** [comment]
I think that I solved all of your last reported issues. Just run http://jsfiddle.net/hvyowrgn/4/ to view the results.
BUT there is one major limitation: If too much line breaks need to be inserted, some text at the end of the cell vanish. This happens, because the height of rows and cells have been calculated by jsPDFAutotable without the knowledge of the new rendering method. In other words, jsPDFAutotable doesn't know about the new lines that will be inserted when tableExport draws the cell text. 
Currently I do not see a reasonable way to solve this issue other than by a major rework of the plugin. That would probably mean to give up the usage of jsPDFAutotable or even to melt the source code of both plugins. I think you feel what that means...   Thanks.

**Comment by mrbeak** [comment]
Dear hhurz,

The plugin is advancing fast. this is super cool. At least for my usecase it's already almost perfect.

About the major issue you mentioned: I think I have two posible ways to make the overflow on the botton of cells at least less likeley to happen:

1. Give the plugin a large rowHeight: "styles": {"overflow": "linebreak", "rowHeight": 25}
(I did that here http://jsfiddle.net/hvyowrgn/5/).
2. Distribute the space for the columns smartly. This works on my first example (http://jsfiddle.net/hvyowrgn/1/) but not in the new one (http://jsfiddle.net/hvyowrgn/5/) anymore (I wonder why?). In my usecase i.e. all but the last column could be quite a bit narrower and give the last column more space. More space for the last column implicies less linebreaks (not less linebreaks caused by br-tags, but less linebreaks of those which are inserted to prevent text overflow, and as far as I understood those ones are the problematic ones, right?)

This second point would be cool to have anyway and resemble the behavior of a modern browser : Having a table with a fixed width but distribute the space for the columns smartly.

Best

**Comment by hhurz** [comment]
Thanks for your suggestions. Column width calculation is done by jsPDFAutotable. I'm not able to infliuence this. There is some logic that prevents dynamic colum width distribution when the total of the minimal column width exceeds the table width, It works for http://jsfiddle.net/hvyowrgn/5/ again, if you switch the page orientation to landscape (http://jsfiddle.net/hvyowrgn/6/). I recommend landscape orientation in your case anyway.
