### ISSUE TITLE
colspan for hidden columns, modifying code prior to export?

### ISSUE THREAD

**Issue by punchi** [hhurz/tableExport.jquery.plugin#220]
I have a table with a hidden column. For display on HTML, the column and its values are hidden, when exporting, they're added (not hidden). The last row sum a result, so I have a <tfoot> with colspan and last column with the sum.

https://jsfiddle.net/c3zsbzt6/

The problem appear when exporting to XLS, the hidden column do not add a "colspan" so, the "hidden" are eliminated but the colspan still with 1 and should be 2.

https://jsfiddle.net/7jx1t07b/

Its possible to use a function to make modification to the code prior to exporting without modifying the HTML code, so the view do not change to the user??

**Comment by hhurz** [comment]
I confirm this issue. Colspan/rowspan values of cells aren't recalculated if there follow normally hidden cells/rows that will be exported. Your suggestion to provide a function to manipulate the html code of the table to export, would be nice, but this plugin requires that the table resides in the dom. Thus any modification would also refelct to the original table. The only way I see would be to make an invisible clone of the table in the dom. This table, which would need a data-tableexport-display="always" attribute, could be modified and be exported then.
Because this seems a bit complicated to me, I decided to provide two new attributes that can be set while building the table to export: ```data-tableexport-colspan``` and ```data-tableexport-rowspan```.  If set both attributes replace the original colspan/rowspan attribute value of the table cell during export.
Usage example:
```html
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th hidden data-tableexport-display="always">Name</th>
      <th>Value</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th colspan="1" data-tableexport-colspan="2" style="text-align:right">Total of all values:</th>
      <th>300</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>123</td>
      <td hidden data-tableexport-display="always">Name1</td>
      <td>200</td>
    </tr>
    <tr>
      <td>456</td>
      <td hidden data-tableexport-display="always">Name2</td>
      <td>100</td>
    </tr>
  </tbody>
</table>
```
Currently these new attributed are only available when exporting in XLS (Excel 2000 html) format.

**Comment by punchi** [comment]
Perfect! so quickly! thanks @hhurz !! :smile:
