### ISSUE TITLE
data-tableexport-value not working

### ISSUE THREAD

**Issue by ShyamKirubha** [hhurz/tableExport.jquery.plugin#237]
I have both export and data-filter-control="select" , and when trying to export, the column header has title and the filter values . 
I tried using data-tableexport-value, but it doesn´t seem to work.

**Comment by ShyamKirubha** [comment]
![image](https://user-images.githubusercontent.com/39969651/43284263-2a375042-9113-11e8-8327-495993e0c4dc.png)

This is my source code, when it is being read by tableExport.js, it doesn´t get the attribute data-tableexport-value.

![image](https://user-images.githubusercontent.com/39969651/43284178-ec69a79c-9112-11e8-9416-97bd556c38cd.png)


Can anyone help with this please?

**Comment by hhurz** [comment]
@ShyamKirubha: To answer your question there is a better description about what you are trying to do required. Also a complete example would be helpfull, not just a fragment of code. Thank you.

**Comment by jvarn** [comment]
Just to note that I experienced this when my table id and data-toggle were lazily set to "table" for testing.
[https://codepen.io/jvarn13/pen/BMNxvz](https://codepen.io/jvarn13/pen/BMNxvz)

It's worth pointing out because in the examples on [bootstrap-table.com](https://bootstrap-table.com/docs/getting-started/usage/#via-data-attributes), "table" is used as the table id.
