### ISSUE TITLE
Modifying attributes with jquery cache issue

### ISSUE THREAD

**Issue by hcglitte** [hhurz/tableExport.jquery.plugin#275]
Hi,

I let the user dynamically alter attributes like data-tableexport-display="none" to data-tableexport-display="always" and etc.

If nothing is altered prior to export, it exports as it should.
Then later an attribute is changed (verified by inspecting).
Then when exporting again, it will just export the same as the first time.

If you change an attribute before exporting for the first time, and then export, it works fine.

It seems that the export function just makes a "copy" of the first exported view, and will ignore if the attributes are changed afterwards.

**Comment by hcglitte** [comment]
The issue was found (perhaps this will be helpful for others):
https://stackoverflow.com/questions/28335833/get-wrong-value-in-data-attribute-jquery

So use data instead of attr or both perhaps:
$(selector).attr("data-tableexport-display", "none or always");
$(selector).data("tableexport-display", "none or always");

**Comment by hhurz** [comment]
Hi, thanks for reporting this issue. The reason for this is that externally changing table data attributes after loading the plugin is not reflected in the jQuery .data() cache. Therefore, the .attr() function of jQuery must be used to access the changed attributes. The issue will be fixed in next release.
