### ISSUE TITLE
Error when I open xlsx file

### ISSUE THREAD

**Issue by algon70** [hhurz/tableExport.jquery.plugin#289]
Hi,
I have an error when I open excel file:
![image](https://user-images.githubusercontent.com/60267318/73085572-2e0d5700-3ecf-11ea-8682-d759920763fd.png)

Thanks

**Comment by hhurz** [comment]
Due to lack of further information I cannot comment on this issue

**Comment by algon70** [comment]
In my webapp I have a bootstrap table, when I export the table with many records (> 1000) Excel gives me an error when opening. The same table with fewer records (200-300) Excel opens correctly

**Comment by algon70** [comment]
I have an update, the size of the table is not the problem. I understand that a single line causes the error. In a field I have "950E2862". 
is it possible for Excel to treat it as a number rather than a string?
How can I tell the exporter that that column is a string and not a number?

**Comment by hhurz** [comment]
Hi, thanks for providing further information that helped to improve the internal number conversion function when exporting to xlsx format. 
With this improvement, I think you do not need to specify an explicit format. If you still want to do so, you can use the html data attribute ```data-tableexport-xlsxformatid``` when building the html table. 
The fix was released with version 1.10.15 of the plugin.

**Comment by algon70** [comment]
Sorry, but what if I wanted to force the field as a string?

**Comment by hhurz** [comment]
Use the html data **attribute data-tableexport-xlsxformatid** like this `<td data-tableexport-xlsxformatid="49">950E2862</td>` Further format id's are listed in README.md
