### ISSUE TITLE
Visual feedback while loading file

### ISSUE THREAD

**Issue by filipesiegrist** [hhurz/tableExport.jquery.plugin#290]
I'm using this library attached with bootstrap-table.
I have really big tables (~8000 rows) and I want to export them into '.xlsx' files.
The table itself is loaded client-side, and the loading time itself isn't a problem.

My goal is to show a loading message while the conversion is done.
I tried using `onBeforeSaveToFile` and `onAfterSaveToFile` messages but the main loading time is before that, at the '.xlsx' conversion.

Sorry if this is repeated, but I  searched about this here, in the bootstrap-table repo (and google, of course), but couldn't find anything.

A callback called 'onBeforeConversion' would very helpful. As I saw on the code, the change is onle adding this option to the API and calling it at the beginning of the code.

Code that I tried. It only showed the loading message while the file was already downloading.
```
'exportOptions': {
    'fileName': 'amr_log',
    'onBeforeSaveToFile': function(){
        swal.fire("Loading file");
        swal.showLoading();
    },
    'onAfterSaveToFile': function() {
        swal.close();
        }
    }
}

**Comment by hhurz** [comment]
Your detailed issue description convinced me to release a new version (1.10.16) that contains two new callback functions: onTableExportBegin and onTableExportEnd. Called when export process starts and ends resp.

**Comment by filipesiegrist** [comment]
Thanks, I'll wait for it.

Edit - I just saw that it was already merged. Thank you. I'll test it as soon as possible.

**Comment by Airforce111** [comment]
Were you able to test out the onTableExportBegin and onTableExportEnd callback functions and did it work?

Seems like onTableExportBegin is being called after the file browser window pops up for my tests.

**Comment by pixelzdesign** [comment]
onTableExportBegin  doesn't work as expected. 
The function should be called after clicking the PDF (Excel...) button, not when the document save dialog is pops up in browser, as now.

**Comment by hhurz** [comment]
This plugin has no kowledge of any visual button that will be or have been clicked. I think what you like to achieve needs to be implemneted around the plugin, in your case within bootstrap table that calls this plugin. 
The onTableExportBegin and onTableExportEnd callbacks just mark the start and end of the plugins export function. They can be used to visualize the progress of a long during export process. But for that the option ```outputMode: 'file'``` of the plugin, which is default, cannot be used, because it would invoke the browsers document save dialog before the export function returns. In this case use the option ```outputMode: 'base64'``` so the plugin doesn't save the export result on its own, but returns it as a base64 encoded string as a result of the export function, that can be saved by the caller.
