### ISSUE TITLE
European characters

### ISSUE THREAD

**Issue by chrisreingruber** [hhurz/tableExport.jquery.plugin#301]
Hi there,

love your work. Though I have problems when exporting to PDF, characters like Ä, Ö, Ü and so on are displayed like "Ã¼", "Ã¶", "Ãœ" etc. 
In my HTML i defined them like `"&auml;",` `"&ouml;"` and `"&uuml;".` Is there a way to handle the encoding? Any other ideas?

**Comment by hhurz** [comment]
Hi, I guess you are exporting to PDF using the jsPDF library (pdfmake would be an alternative). jsPDF has only limited capabilities to output non ASCII charachters which is a known issue of this library. 
BUT it especially supports umlaut's and some other commonly used "european characters". 
Any way, here is an example PDF output of one of my test tables:

![jspdf](https://user-images.githubusercontent.com/4164372/83061483-5cf23000-a05d-11ea-9365-6e751248c106.png)

The html of the cell containing the umlaut's is `<td>Deutsch (Ää&auml;Öö&ouml;Üü&uuml;ß)</td>`
As you can see I'm not able to reproduce your problem because I use UTF-8 as character encoding for the html page. I assume that you are using "windows-1252" or "ISO-8859-1" as character encoding. 
You should specify the <meta> tag as `<meta charset="UTF-8">`
