### ISSUE TITLE
Exporting to xlshtml gives "warning" when opening xls file in Excel

### ISSUE THREAD

**Issue by Bachstelze** [hhurz/tableExport.jquery.plugin#324]
Excel says that the format and extension are not merging.
My code:
```
$( document ).ready(function() {
    var exel_file_name = '{{ project }}_{% now "jS_F_Y" %}';
    $('#output_table').tableExport({type:'excel', fileName: exel_file_name, mso: {fileFormat:'xlshtml'}}); 
});
```

**Comment by hhurz** [comment]
This behavior is an Excel "feature"... Explanation copied from README.md:

Excel Notes
===========

When exporting in Excel 2000 html format (xlshtml) the default extension of the result file is XLS although the type of the file content is HTML. When you open a file in Microsoft Office Excel 2007 or later that contains content that does not match the files extension, you receive the following warning message:
```The file you are trying to open, 'name.ext', is in a different format than specified by the file extension. Verify that the file is not corrupted and is from a trusted source before opening the file. Do you want to open the file now?```
According to this [Knowledge base article](https://support.microsoft.com/en-us/help/948615/error-opening-file-the-file-format-differs-from-the-format-that-the-fi) The warning message can help prevent unexpected problems that might occur because of possible incompatibility between the actual content of the file and the file name extension. The article also gives you some hints to disable the warning message.

**Comment by Bachstelze** [comment]
Ok, i don't understand this, but thank you!
