### ISSUE TITLE
Ignoring a column during export

### ISSUE THREAD

**Issue by waspinator** [hhurz/tableExport.jquery.plugin#34]
I've got some action buttons in a column in each one of my rows. Is there a way I can remove the entire row from being exported, instead of the individual cells?

For example

`<th data-field="action-buttons" data-tableexport-display="none"></th>`

Thanks

**Comment by hhurz** [comment]
There are two solutions for this task:
1. Use the ignoreRow option, e.g. `ignoreRow: [0,1]` to exclude the first two rows from export
2. Add `data-tableexport-display="none"` to each cell of the row that you don't want to export

Actually there is no data attribute you could add to the row tag. I think i will add such one in the next version of the plugin.

**Comment by waspinator** [comment]
Thanks, the ignoreRow/Column option worked. I actually misspoke and meant to say 'remove the entire column' but it's the same general idea.
On a related note, I built my tables using data attributes instead of javascript, and I can't seem to modify export options. For example this doesn't change the file name or ignore the selected column (the export button and types work correctly):

```
<table id="table"
       data-show-export="true"
       data-export-types="['csv']"
       data-export-options="{fileName: 'myExportName', ignoreColumn: [4]}"
>
```

Should that be possible, or can I only do that in javascript?

Thanks

**Comment by hhurz** [comment]
There is currently only one data attribute you can use while generating the table: `tableexport-display`. To set all other options you have to use javascript.

**Comment by zolrag13** [comment]
Hi,

I don't know if I should open a new issue but I have a question which is related to this issue. I will happily open a different issue if necessary.

Anyway, it seems that ignoreRow doesn't work too well with showColumns. 
For example, if you use ```ignoreRow: [0, 2]``` and the user decide to use the showColumns dropdown to hide column 0, the resulting columns in the csv will be shifted ignoring column 1 and 3 instead of the hidden 0 and 2 which is not the expected behavior I think.

Is it possible to ignore columns by name instead of index?

Thank you
