### ISSUE TITLE
How to export values to XLSX as currency format?

### ISSUE THREAD

**Issue by CryptocurrencyZ** [hhurz/tableExport.jquery.plugin#350]

**Comment by hhurz** [comment]
The currency format is not supported by the current version.

**Comment by hhurz** [comment]
Version 1.26.0 contains a new option mso.xlsx.formatid.currency, which allows you to specify the format string for exporting currency values. 

Since currency values cannot be detected automatically, cells containing currency values must be marked with the data attribute 'tableexport-xlsxformatid' set to 164. Example `<td data-tableexport-xlsxformatid="164">1.84</td>`

The default format string used for mso.xlsx.formatid.currency is `'$#,##0.00;[Red]-$#,##0.00'`, which you can of course customize for your needs. For Euro you could use `'#,##0.00 €;[Red](#,##0.00) €'`
