### ISSUE TITLE
NPM 

### ISSUE THREAD

**Issue by talatbaig** [hhurz/tableExport.jquery.plugin#82]
Hi,

Could you add this package to npm so that I can install using npm install 

Thanks

**Comment by talatbaig** [comment]
Hi,

Thanks for the package.json file, I still seem to have issues with the following
`npm install git+https://github.com/hhurz/tableExport.jquery.plugin.git`

this seems to be the issue
`'file-saver.js' is not in the npm registry.`

**Comment by hhurz** [comment]
Hi, thanks for your suggestion and your hints. You are right the package name should be 'filesaver.js'. Fixed it.

**Comment by talatbaig** [comment]
thank you!

**Comment by joancifo** [comment]
I'm curious:

Why 'filesaver.js' is a dependency instead of 'file-saver'? (the first seems a unmaintained fork from the second)

And npm fails when try to install because it can find a version for html2canvas.

Thanks!

**Comment by hhurz** [comment]
This plugin uses [eligrey/FileSaver.js](https://github.com/eligrey/FileSaver.js) which is definitely a well maintained project, The other project you mentioned seems to be this one [alferov/angular-file-saver](https://github.com/alferov/angular-file-saver) which I don't know and don't use.
Regarding html2canvas I'm not able to give any support because I don't use npm by myself. Thus any help would be appreciated...

**Comment by joancifo** [comment]
Oops, sorry.

I was thinking that the dependencies of package.json were from npm repository. So:
"filesaver.js": "*" => https://www.npmjs.com/package/filesaver.js that is https://github.com/mWater/FileSaver.js 

But what I mean, "file-saver" => https://www.npmjs.com/package/file-saver that is https://github.com/eligrey/FileSaver.js

And the dependency of html2canvas could be 0.5.0-beta4 or something.

Thank you!

**Comment by hhurz** [comment]
@kanashin: Thanks for pointing that out to me. Just reworked the package dependencies and published a new release version 1.6.4
